---
title: "Random Forest Models"
author: "Belle Schmidt"
date: "2024-07-16"
output: html_document
---

# Libraries 
```{r}
# install.packages("stacks")
library(tidyverse)
theme_set(theme_bw())
library(stacks)
library(ranger)
library(vip)
```

# Read in the dataset & Clean For Random Forest Model
```{r}
Overall_Stats <- read.csv("mlb_pitching_stats_2020-24.csv")

Cleaned_Data <- Overall_Stats |> 
  filter(pitch_name == "4-Seam Fastball", !is.na(stuff_plus), season == 2021) |> 
  select(spin, velocity, extension, induced_vertical_break, horizontal_break, stuff_plus)
```

# Fitting A Plain Random Forest Model With No Tuning
```{r}

Stuff_Plus_rf <- ranger(stuff_plus ~ spin + velocity + extension + induced_vertical_break + horizontal_break, 
                   num.trees = 1000, importance = "impurity", data = Cleaned_Data)

Stuff_Plus_rf
```
# Variable of Importance Graph
```{r}
vip(Stuff_Plus_rf)
```

# Random Standard Error
```{r}
Cleaned_Data |> 
  mutate(pred = Stuff_Plus_rf$predictions) |> 
  summarize(rmse = sqrt(mean((stuff_plus - pred) ^ 2)))
```

```{r}
Cleaned_Data|>
  mutate(pred = Stuff_Plus_rf$predictions) |>
  ggplot(aes(stuff_plus, pred)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red")
```

