---
title: "Slider Graphs"
author: "Belle Schmidt"
date: "2024-07-09"
output: html_document
---

### Libraries

```{r}
library(tidyverse)
library(ggridges)
library(ggthemes)
library(pillar)
library(baseballr)
library(readr)
library(viridis)
```


### Filtering Pitchers For IP & Times The Pitcher Throws The Pitch

```{r}
Joined_FanGraphs_Statcast_SL <- Joined_FanGraphs_Statcast |> 
  filter(IP >= 21.1, times_thrown_SL >= 100) 
```


### Relationship Between A Pitcher's Average Velocity and Outcome Variables For A Slider


```{r}
# Relationship Between A Pitcher's Average 4-Seam Fastball Velocity And Its Average Stuff+

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_velocity_SL, y = stuff_plus_stuff_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Average Stuff+",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Average Stuff+") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(ylim = c(50, 175)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 12),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Velocity And Its Run Value Per 100 Pitches

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_velocity_SL, y = run_value_per100_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Run Value Per 100 Pitches",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Run Value Per 100 Pitches") +
  coord_cartesian(ylim = c(-20, 15)) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11.2),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Velocity And Its Swing Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_velocity_SL, y = swing_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Swing Rate",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Swing Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 13),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Velocity And Its Swing And Miss Percentage

Joined_FanGraphs_Statcast_SL |> 
  mutate(swing_and_miss_pct_SL = (swing_and_miss_pct_SL / 100)) |>
  ggplot(aes(x = avg_velocity_SL, y = swing_and_miss_pct_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Swing & Miss Percentage",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Swing And Miss Percentage") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(ylim = c(0, .50)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11.2),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Velocity And WIFF Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_velocity_SL, y = wiff_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Wiff Rate",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Wiff Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
    coord_cartesian(ylim = c(0, .6)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 13.5),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Velocity And Average WOBA Value

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_velocity_SL, y = avg_WOBA_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Velocity And Its Average WOBA Value",
       x = "Pitcher's Average Velocity",
       y = "Pitcher's Average WOBA Value") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(ylim = c(0, .85)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11.5),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

### Relationship Between A Pitcher's Average Vertical Break and Outcome Variables For A Slider

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And Its Average Stuff+

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_v_break_SL, y = stuff_plus_stuff_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Average Stuff+",
       x = "Pitcher's Average Vertical Break",
       y = "Pitcher's Average Stuff+") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-1, 1.3), ylim = c(20, 200)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 12),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And Its Run Value Per 100 Pitches

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_v_break_SL, y = run_value_per100_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Run Value Per 100 Pitches",
       x = "Pitcher's Average Veritcal Break",
       y = "Pitcher's Run Value Per 100 Pitches") +
  coord_cartesian(xlim = c(-1, 1.3), ylim = c(-15, 15)) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 10.7),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And Its Swing Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_v_break_SL, y = swing_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Swing Rate",
       x = "Pitcher's Average Veritcal Break",
       y = "Pitcher's Swing Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-1, 1.3)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 12),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And Its Swing And Miss Percentage

Joined_FanGraphs_Statcast_SL |> 
  mutate(swing_and_miss_pct_SL = (swing_and_miss_pct_SL / 100)) |>
  ggplot(aes(x = avg_v_break_SL, y = swing_and_miss_pct_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Swing & Miss Percentage",
       x = "Pitcher's Average Vertical Break",
       y = "Pitcher's Swing And Miss Percentage") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-1, 1.3), ylim = c(0, .35)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 10),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And WIFF Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_v_break_SL, y = wiff_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Wiff Rate",
       x = "Pitcher's Average Vertical Break",
       y = "Pitcher's Wiff Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
    coord_cartesian(xlim = c(-1, 1.3), ylim = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 12.5),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Vertical Break And Average WOBA Value

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_v_break_SL, y = avg_WOBA_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Vertical Break And Its Average WOBA Value",
       x = "Pitcher's Average Vertical Break",
       y = "Pitcher's Average WOBA Value") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-1, 1.3), ylim = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```


### Relationship Between A Pitcher's Average Horizontal Break and Outcome Variables For A Slider

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And Its Average Stuff+

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_h_break_SL, y = stuff_plus_stuff_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Average Stuff+",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Average Stuff+") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-2, 1.75), ylim = c(20, 190)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11.2),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And Its Run Value Per 100 Pitches

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_h_break_SL, y = run_value_per100_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Run Value Per 100 Pitches",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Run Value Per 100 Pitches") +
  coord_cartesian(xlim = c(-2, 1.75), ylim = c(-15, 15)) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 10.1),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And Its Swing Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_h_break_SL, y = swing_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Swing Rate",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Swing Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-2, 1.75)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And Its Swing And Miss Percentage

Joined_FanGraphs_Statcast_SL |> 
  mutate(swing_and_miss_pct_SL = (swing_and_miss_pct_SL / 100)) |>
  ggplot(aes(x = avg_h_break_SL, y = swing_and_miss_pct_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Swing & Miss Percentage",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Swing And Miss Percentage") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-2, 1.75), ylim = c(0, .45)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 10),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And WIFF Rate

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_h_break_SL, y = wiff_rate_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Wiff Rate",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Wiff Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
    coord_cartesian(xlim = c(-2, 1.75), ylim = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 12),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```

```{r}
# Relationship Between A Pitcher's Average Slider Horizontal Break And Average WOBA Value

Joined_FanGraphs_Statcast_SL |> 
  ggplot(aes(x = avg_h_break_SL, y = avg_WOBA_SL)) +
  geom_point(aes(color = Season), alpha = .3) +
  facet_wrap(~Season) +
  labs(title = "Relationship Between A Pitcher's Average Slider Horizontal Break And Its Average WOBA Value",
       x = "Pitcher's Average Horizontal Break",
       y = "Pitcher's Average WOBA Value") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  coord_cartesian(xlim = c(-2, 1.75), ylim = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 11),
        axis.title = element_text(face = "bold", size = 12),
        axis.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 12,lineheight = 3.0),
strip.background = element_rect(fill = "steelblue4", colour = "black"),
strip.text.x = element_text(color = "white")) 
```